name: design living
favicon: null
layout_spectrum: 0
typography_spectrum: 0.00036
title: designing experiences for new interactions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0b0b'
    - '#d8e2ed'
    - '#a8aeae'
    - '#696f61'
    - '#474b4a'
  brandStrength: 0.7353296969085932
  lightness: 0.375
  saturation: 0.6365252069663256
  rhythmicContrast: 1
purpose: []
